services:
  mysql-server:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5555:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - adminer-network

  adminer:
    image: adminer
    ports:
      - 8000:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      - mysql-server
    networks:
      - adminer-network
volumes:
  mysql-data:

networks:
  adminer-network:
